# Generated by Django 6.0.3 on 2026-03-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(default='NA'),
        ),
    ]
